using PdfSharpCore.Drawing;
using PdfSharpCore.Pdf;
using System.Text;

namespace PdfTester;

internal class Program
{
    static void Main(string[] args)
    {
        // Register encoding provider for PDFSharp compatibility
        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

        Console.WriteLine("Starting PDF Generation Test...");

        // Create the PDF service
        var pdfService = new PdfService();

        // Test 1: Simple Employee List (Basic)
        Console.WriteLine("\n[Test 1] Generating PDF with employee data...");
        var employees = GenerateEmployees(50);

        var options1 = new PdfService.PdfOptions
        {
            Title = "Employee Report - 50 Rows",
            TableFontSize = 10,
            UseExcelLikeSizing = true,
            HeaderLines = new List<string>
            {
                "Company Name: **Acme Corporation**",
                "Report Date: **February 24, 2026**",
                "Department: All Departments"
            },
            DisclaimerLines = new List<string>
            {
                "**CONFIDENTIAL DOCUMENT** - This document contains proprietary information.",
                "Unauthorized distribution is **strictly prohibited**.",
                "Generated by: Automated PDF Service v1.0"
            }
        };

        pdfService.GeneratePdf(employees, "output_employees.pdf", options1);
        Console.WriteLine($"✓ Generated: output_employees.pdf ({new FileInfo("output_employees.pdf").Length} bytes)");

        // Test 2: Generic Product List (Any type of objects)
        Console.WriteLine("\n[Test 2] Generating PDF with product data...");
        var products = GenerateProducts(30);

        var options2 = new PdfService.PdfOptions
        {
            Title = "Product Inventory Report",
            TableFontSize = 9,
            UseExcelLikeSizing = true,
            HeaderLines = new List<string>
            {
                "Warehouse: **Main Distribution Center**",
                "Report Type: **Inventory Summary**",
                "Generated by: System Administrator"
            },
            DisclaimerLines = new List<string>
            {
                "This report is **internal use only**.",
                "Contact **inventory@company.com** for questions."
            }
        };

        pdfService.GeneratePdf(products, "output_products.pdf", options2);
        Console.WriteLine($"✓ Generated: output_products.pdf ({new FileInfo("output_products.pdf").Length} bytes)");

        // Test 3: Student Records with Multiple Header/Disclaimer Rows
        Console.WriteLine("\n[Test 3] Generating PDF with student data...");
        var students = GenerateStudents(25);

        var options3 = new PdfService.PdfOptions
        {
            Title = "Student Academic Report",
            TableFontSize = 10,
            UseExcelLikeSizing = true,
            HeaderLines = new List<string>
            {
                "School: **Springfield Academy**",
                "Academic Year: **2025-2026**",
                "Semester: Spring 2026",
                "Report Generated by: **Registrar's Office**"
            },
            DisclaimerLines = new List<string>
            {
                "**OFFICIAL RECORD** - Document is confidential.",
                "Grade information is **final and binding**.",
                "Questions? Contact registrar@school.edu",
                "© 2026 Springfield Academy. All rights reserved."
            }
        };

        pdfService.GeneratePdf(students, "output_students.pdf", options3);
        Console.WriteLine($"✓ Generated: output_students.pdf ({new FileInfo("output_students.pdf").Length} bytes)");

        // Test 4: Service returning byte array
        Console.WriteLine("\n[Test 4] Testing byte array return...");
        var pdfBytes = pdfService.GeneratePdf(GenerateEmployees(10), new PdfService.PdfOptions
        {
            Title = "Byte Array Test",
            HeaderLines = new List<string> { "Test: **Byte Array Generation**" }
        });
        Console.WriteLine($"✓ Generated byte array: {pdfBytes.Length} bytes");

        // Test 5: Migrated PdfExportService with column definitions
        Console.WriteLine("\n[Test 5] Testing migrated PdfExportService from Umbraco...");
        var pdfExportService = new PdfExportService();
        var funds = GenerateFunds(40);

        var columns = new List<PdfColumnDefinition>
        {
            new() { PropertyName = "FundName", HeaderText = "Fund Name", Alignment = XStringAlignment.Near },
            new() { PropertyName = "TickerCode", HeaderText = "Ticker", Alignment = XStringAlignment.Center },
            new() { PropertyName = "NavPrice", HeaderText = "NAV Price", Format = "F2", Alignment = XStringAlignment.Far },
            new() { PropertyName = "MarketPrice", HeaderText = "Market Price", Format = "F2", Alignment = XStringAlignment.Far, ShowAverage = true },
            new() { PropertyName = "HoldInTrust", HeaderText = "Hold In Trust", Alignment = XStringAlignment.Near }
        };

        var exportOptions = new PdfExportOptions
        {
            ReportTitle = "FUND SUMMARY REPORT",
            HeaderLines = new List<string>
            {
                "Migrated from Umbraco13",
                "This report provides a summary of all funds including their NAV and market prices."
            },
            DisclaimerLines = new List<string>
            {   
                "",
                "This document is **confidential** and intended for internal use only.",
                "This document is **confidential** and intended for internal use only2."
            },
            ShowAverageRow = false,
            ItemsPerPage = 80,
            ShowHeadingBorders = true,
            ShowDisclaimerBorders = true,
            LastRow = new PdfLastRowDefinition
            {
                CellValues = new List<string>
                {
                    "Total","","","100",""
                }
            }
        };

        var exportedPdf = pdfExportService.ExportToPdf(funds, columns, exportOptions);
        File.WriteAllBytes("output_funds_export.pdf", exportedPdf);
        Console.WriteLine($"✓ Generated: output_funds_export.pdf ({new FileInfo("output_funds_export.pdf").Length} bytes)");

        Console.WriteLine("\n" + new string('=', 50));
        Console.WriteLine("All PDF generation tests completed successfully!");
        Console.WriteLine($"Total files generated: 4");
        Console.WriteLine("File locations:");
        Console.WriteLine($"  - output_employees.pdf");
        Console.WriteLine($"  - output_products.pdf");
        Console.WriteLine($"  - output_students.pdf");
        Console.WriteLine($"  - output_funds_export.pdf (migrated service)");
    }

    // Helper methods to generate test data
    static List<Employee> GenerateEmployees(int count)
    {
        string[] departments = { "Engineering", "Sales", "Marketing", "HR", "Finance" };
        var employees = new List<Employee>();

        for (int i = 1; i <= count; i++)
        {
            employees.Add(new Employee
            {
                Id = i,
                Name = $"Employee {i}",
                Email = $"employee{i}@company.com",
                Department = departments[i % departments.Length],
                Salary = 50000 + i * 1000,
                HireDate = new DateTime(2020, 1, 1).AddMonths(i)
            });
        }
        return employees;
    }

    static List<Product> GenerateProducts(int count)
    {
        string[] categories = { "Electronics", "Clothing", "Food", "Books", "Tools" };
        var products = new List<Product>();

        for (int i = 1; i <= count; i++)
        {
            products.Add(new Product
            {
                Sku = $"SKU-{1000 + i}",
                Name = $"Product {i}",
                Category = categories[i % categories.Length],
                Price = 9.99m + i * 5,
                StockQuantity = 10 + i * 2,
                Supplier = $"Supplier {(i % 5) + 1}"
            });
        }
        return products;
    }

    static List<Student> GenerateStudents(int count)
    {
        string[] majors = { "Computer Science", "Mathematics", "Physics", "Chemistry", "Biology" };
        var students = new List<Student>();

        for (int i = 1; i <= count; i++)
        {
            students.Add(new Student
            {
                StudentId = $"S{1000 + i}",
                FirstName = $"Student{i}",
                LastName = $"Last{i}",
                Major = majors[i % majors.Length],
                Gpa = 2.0 + (i % 40) * 0.05,
                CreditsCompleted = 30 + i * 3
            });
        }
        return students;
    }

    static List<Fund> GenerateFunds(int count)
    {
        string[] trustOptions = { "Yes", "No", "Partial" };
        var funds = new List<Fund>();
        var random = new Random(42); // Fixed seed for reproducibility

        for (int i = 1; i <= count; i++)
        {
            funds.Add(new Fund
            {
                FundName = $"Fund {i} - {(i % 3 == 0 ? "Growth" : i % 2 == 0 ? "Value" : "Balanced")}",
                TickerCode = $"FND{i:D3}",
                NavPrice = 10 + random.NextDouble() * 90,
                MarketPrice = 10 + random.NextDouble() * 90,
                HoldInTrust = trustOptions[i % trustOptions.Length]
            });
        }
        return funds;
    }
}

// Data models
public class Employee
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string Department { get; set; } = string.Empty;
    public decimal Salary { get; set; }
    public DateTime HireDate { get; set; }
}

public class Product
{
    public string Sku { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public int StockQuantity { get; set; }
    public string Supplier { get; set; } = string.Empty;
}

public class Student
{
    public string StudentId { get; set; } = string.Empty;
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    public string Major { get; set; } = string.Empty;
    public double Gpa { get; set; }
    public int CreditsCompleted { get; set; }
}

public class Fund
{
    public string FundName { get; set; } = string.Empty;
    public string TickerCode { get; set; } = string.Empty;
    public double NavPrice { get; set; }
    public double MarketPrice { get; set; }
    public string HoldInTrust { get; set; } = string.Empty;
}
