using PdfSharp.Drawing;
using System.Text;

namespace PdfTester;

internal class Program
{
    static void Main(string[] args)
    {
        // Register encoding provider for PDFSharp compatibility
        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

        Console.WriteLine("Starting PDF Generation Test...");

        // Create the PDF service
        var pdfService = new PdfService();

        // Test 1: Simple Employee List (Basic)
        Console.WriteLine("\n[Test 1] Generating PDF with employee data...");
        var employees = GenerateEmployees(50);

        var options1 = new PdfService.PdfOptions
        {
            Title = "Employee Report - 50 Rows",
            TableFontSize = 10,
            UseExcelLikeSizing = true,
            HeaderLines = new List<string>
            {
                "Company Name: **Acme Corporation**",
                "Report Date: **February 24, 2026**",
                "Department: All Departments"
            },
            DisclaimerLines = new List<string>
            {
                "**CONFIDENTIAL DOCUMENT** - This document contains proprietary information.",
                "Unauthorized distribution is **strictly prohibited**.",
                "Generated by: Automated PDF Service v1.0"
            }
        };

        pdfService.GeneratePdf(employees, "output_employees.pdf", options1);
        Console.WriteLine($"✓ Generated: output_employees.pdf ({new FileInfo("output_employees.pdf").Length} bytes)");

        // Test 2: Generic Product List (Any type of objects)
        Console.WriteLine("\n[Test 2] Generating PDF with product data...");
        var products = GenerateProducts(30);

        var options2 = new PdfService.PdfOptions
        {
            Title = "Product Inventory Report",
            TableFontSize = 9,
            UseExcelLikeSizing = true,
            HeaderLines = new List<string>
            {
                "Warehouse: **Main Distribution Center**",
                "Report Type: **Inventory Summary**",
                "Generated by: System Administrator"
            },
            DisclaimerLines = new List<string>
            {
                "This report is **internal use only**.",
                "Contact **inventory@company.com** for questions."
            }
        };

        pdfService.GeneratePdf(products, "output_products.pdf", options2);
        Console.WriteLine($"✓ Generated: output_products.pdf ({new FileInfo("output_products.pdf").Length} bytes)");

        // Test 3: Student Records with Multiple Header/Disclaimer Rows
        Console.WriteLine("\n[Test 3] Generating PDF with student data...");
        var students = GenerateStudents(25);

        var options3 = new PdfService.PdfOptions
        {
            Title = "Student Academic Report",
            TableFontSize = 10,
            UseExcelLikeSizing = true,
            HeaderLines = new List<string>
            {
                "School: **Springfield Academy**",
                "Academic Year: **2025-2026**",
                "Semester: Spring 2026",
                "Report Generated by: **Registrar's Office**"
            },
            DisclaimerLines = new List<string>
            {
                "**OFFICIAL RECORD** - Document is confidential.",
                "Grade information is **final and binding**.",
                "Questions? Contact registrar@school.edu",
                "© 2026 Springfield Academy. All rights reserved."
            }
        };

        pdfService.GeneratePdf(students, "output_students.pdf", options3);
        Console.WriteLine($"✓ Generated: output_students.pdf ({new FileInfo("output_students.pdf").Length} bytes)");

        // Test 4: Service returning byte array
        Console.WriteLine("\n[Test 4] Testing byte array return...");
        var pdfBytes = pdfService.GeneratePdf(GenerateEmployees(10), new PdfService.PdfOptions
        {
            Title = "Byte Array Test",
            HeaderLines = new List<string> { "Test: **Byte Array Generation**" }
        });
        Console.WriteLine($"✓ Generated byte array: {pdfBytes.Length} bytes");

        // Test 5: Migrated PdfExportService with column definitions
        Console.WriteLine("\n[Test 5] Testing migrated PdfExportService from Umbraco...");
        var pdfExportService = new PdfExportService();
        var funds = GenerateFunds(40);

            var columns = new List<PdfColumnDefinition>
            {
                new() { PropertyName = "SecurityName", HeaderText = "Security Name", Alignment = XStringAlignment.Near },
                new() { PropertyName = "SecurityIdentifier", HeaderText = "Security Identifier", Alignment = XStringAlignment.Near },
                new() { PropertyName = "PortfolioWeighting", HeaderText = "Portfolio Weighting", Alignment = XStringAlignment.Near, Format = "F2" },
                new() { PropertyName = "NumberOfShares", HeaderText = "Number of Shares", Alignment = XStringAlignment.Near, Format = "N0" }
            };

                // Configure export options
                var options = new PdfExportOptions
                {
                    ItemsPerPage = 92,
                    HeaderLines = new List<string> {
                    $"List of Portfolio Holdings",
                },
                    DisclaimerLines = new List<string> {
                    "",
                    "Portfolio holdings are subject to change and should not be considered a recommendation to buy or",
                    "sell individual securities.",
                    "",
                    "**Investors should carefully consider investment objectives, risks, charges and expenses.**",
                    "**This and other important information is contained in the fund prospectus which should be**",
                    "**considered carefully before investing. Click here to obtainthe prospectus or call 888.622.1813.**",
                    "",
                    "Past performance is not a guarantee of future results. All data is in U.S. dollars unless otherwise noted. The",
                    "Fund invests ingold and other precious metals, which involves additional and special risks, such as the",
                    "possibility for substantial pricefluctuations over a short period of time; the market for gold/precious metals",
                    "is relatively limited; the sources of gold/preciousmetals are concentrated in countries that have the potential",
                    "for instability; and the market for gold/precious metals isunregulated. The Fund may also invest in foreign",
                    "securities, which are subject to special risks including: differences inaccounting methods; the value of foreign",
                    "currencies may decline relative to the U.S. dollar; a foreign government mayexpropriate the Fund’s assets; and",
                    "political, social or economic instability in a foreign country in which the Fund invests maycause the value of",
                    "the Fund’s investments to decline. The Fund is non-diversified, meaning it may concentrate its assets infewer",
                    "individual holdings than a diversified fund. Therefore, the Fund is more exposed to individual stock volatility",
                    "than adiversified fund."
                    ,"",
                    $"© {DateTime.Now.Year} Sprott Inc. All rights reserved."
                },

                    LastRow = new PdfLastRowDefinition
                    {
                        CellValues = new List<string>
                    {
                        "",
                        "",
                        " 100%",
                        ""
                    },
                    },
                    Author = "Sprott Inc.",
                    ShowHeadingBorders = true,
                    ShowDisclaimerBorders = true,
                    HeadingHeightPixels = 20,
                    TableMinimalWidthPixels = 220
                };
                
                options.ReportTitle = $"Sprott Focus Trust (FUND)";
                
                options.DocumentTitle = options.ReportTitle;

        var exportedPdf = pdfExportService.ExportToPdf(funds, columns, options);
        File.WriteAllBytes("output_funds_export.pdf", exportedPdf);
        Console.WriteLine($"✓ Generated: output_funds_export.pdf ({new FileInfo("output_funds_export.pdf").Length} bytes)");

        // Test 6: Custom column widths with long text in first column
        Console.WriteLine("\n[Test 6] Testing custom column widths with long text...");
        var descriptions = GenerateDescriptions(20);

        var columns6 = new List<PdfColumnDefinition>
        {
            new() { PropertyName = "Description", HeaderText = "Description", Width = 280, Alignment = XStringAlignment.Near },
            new() { PropertyName = "Category", HeaderText = "Category", Width = 80, Alignment = XStringAlignment.Center },
            new() { PropertyName = "Priority", HeaderText = "Priority", Width = 60, Alignment = XStringAlignment.Center },
            new() { PropertyName = "Status", HeaderText = "Status", Width = 70, Alignment = XStringAlignment.Center }
        };

        var options6 = new PdfExportOptions
        {
            ItemsPerPage = 25,
            ReportTitle = "Task Description Report",
            HeaderLines = new List<string>
            {
                "Project: System Documentation Project",
                "Report Date: " + DateTime.Now.ToString("MMMM dd, yyyy"),
                "Showing detailed descriptions with custom column widths"
            },
            DisclaimerLines = new List<string>
            {
                "",
                "This report demonstrates custom column width specification.",
                "The first column has a fixed width of 280 units for long descriptions.",
                "Other columns have smaller fixed widths as appropriate."
            },
            Author = "Documentation Team",
            TableMinimalWidthPixels = 490,
            ShowHeadingBorders = true
        };

        var pdf6 = pdfExportService.ExportToPdf(descriptions, columns6, options6);
        File.WriteAllBytes("output_custom_widths.pdf", pdf6);
        Console.WriteLine($"✓ Generated: output_custom_widths.pdf ({new FileInfo("output_custom_widths.pdf").Length} bytes)");

        Console.WriteLine("\n" + new string('=', 50));
        Console.WriteLine("All PDF generation tests completed successfully!");
        Console.WriteLine($"Total files generated: 5");
        Console.WriteLine("File locations:");
        Console.WriteLine($"  - output_employees.pdf");
        Console.WriteLine($"  - output_products.pdf");
        Console.WriteLine($"  - output_students.pdf");
        Console.WriteLine($"  - output_funds_export.pdf (migrated service)");
        Console.WriteLine($"  - output_custom_widths.pdf (custom column widths)");
    }

    // Helper methods to generate test data
    static List<Employee> GenerateEmployees(int count)
    {
        string[] departments = { "Engineering", "Sales", "Marketing", "HR", "Finance" };
        var employees = new List<Employee>();

        for (int i = 1; i <= count; i++)
        {
            employees.Add(new Employee
            {
                Id = i,
                Name = $"Employee {i}",
                Email = $"employee{i}@company.com",
                Department = departments[i % departments.Length],
                Salary = 50000 + i * 1000,
                HireDate = new DateTime(2020, 1, 1).AddMonths(i)
            });
        }
        return employees;
    }

    static List<Product> GenerateProducts(int count)
    {
        string[] categories = { "Electronics", "Clothing", "Food", "Books", "Tools" };
        var products = new List<Product>();

        for (int i = 1; i <= count; i++)
        {
            products.Add(new Product
            {
                Sku = $"SKU-{1000 + i}",
                Name = $"Product {i}",
                Category = categories[i % categories.Length],
                Price = 9.99m + i * 5,
                StockQuantity = 10 + i * 2,
                Supplier = $"Supplier {(i % 5) + 1}"
            });
        }
        return products;
    }

    static List<Student> GenerateStudents(int count)
    {
        string[] majors = { "Computer Science", "Mathematics", "Physics", "Chemistry", "Biology" };
        var students = new List<Student>();

        for (int i = 1; i <= count; i++)
        {
            students.Add(new Student
            {
                StudentId = $"S{1000 + i}",
                FirstName = $"Student{i}",
                LastName = $"Last{i}",
                Major = majors[i % majors.Length],
                Gpa = 2.0 + (i % 40) * 0.05,
                CreditsCompleted = 30 + i * 3
            });
        }
        return students;
    }

    static List<Fund> GenerateFunds(int count)
    {
        string[] trustOptions = { "Yes", "No", "Partial" };
        var funds = new List<Fund>();
        var random = new Random(42); // Fixed seed for reproducibility

        for (int i = 1; i <= count; i++)
        {
            funds.Add(new Fund
            {
                FundName = $"Fund {i} - {(i % 3 == 0 ? "Growth" : i % 2 == 0 ? "Value" : "Balanced")}",
                TickerCode = $"FND{i:D3}",
                NavPrice = 10 + random.NextDouble() * 90,
                MarketPrice = 10 + random.NextDouble() * 90,
                HoldInTrust = trustOptions[i % trustOptions.Length]
            });
        }
        return funds;
    }

    static List<TaskDescription> GenerateDescriptions(int count)
    {
        string[] categories = { "Documentation", "Development", "Testing", "Deployment", "Maintenance" };
        string[] priorities = { "High", "Medium", "Low" };
        string[] statuses = { "Pending", "In Progress", "Completed", "Blocked" };

        var tasks = new List<TaskDescription>();
        string[] longDescriptions = new[]
        {
            "Implement comprehensive user authentication system with multi-factor support and password reset functionality.",
            "Design RESTful API endpoints for user management including CRUD operations and search functionality.",
            "Create detailed technical documentation for system architecture, database schemas, and API specifications.",
            "Optimize database query performance by implementing indexing strategies and caching mechanisms.",
            "Develop automated testing suite covering unit tests, integration tests, and end-to-end tests.",
            "Implement real-time data synchronization across multiple client devices using WebSocket connections.",
            "Build responsive user interface components with accessibility support and localization.",
            "Set up continuous integration and deployment pipeline with automated testing and code quality checks.",
            "Conduct security audit implementing input validation, SQL injection prevention, and XSS protection.",
            "Design scalable microservices architecture with service discovery and load balancing."
        };

        for (int i = 1; i <= count; i++)
        {
            tasks.Add(new TaskDescription
            {
                Description = longDescriptions[(i - 1) % longDescriptions.Length] + $" (Task #{i})",
                Category = categories[i % categories.Length],
                Priority = priorities[i % priorities.Length],
                Status = statuses[i % statuses.Length]
            });
        }
        return tasks;
    }
}

// Data models
public class Employee
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string Department { get; set; } = string.Empty;
    public decimal Salary { get; set; }
    public DateTime HireDate { get; set; }
}

public class Product
{
    public string Sku { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public decimal Price { get; set; }
    public int StockQuantity { get; set; }
    public string Supplier { get; set; } = string.Empty;
}

public class Student
{
    public string StudentId { get; set; } = string.Empty;
    public string FirstName { get; set; } = string.Empty;
    public string LastName { get; set; } = string.Empty;
    public string Major { get; set; } = string.Empty;
    public double Gpa { get; set; }
    public int CreditsCompleted { get; set; }
}

public class Fund
{
    public string FundName { get; set; } = string.Empty;
    public string TickerCode { get; set; } = string.Empty;
    public double NavPrice { get; set; }
    public double MarketPrice { get; set; }
    public string HoldInTrust { get; set; } = string.Empty;
}

public class TaskDescription
{
    public string Description { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string Priority { get; set; } = string.Empty;
    public string Status { get; set; } = string.Empty;
}
